export enum BEER_EVENTS {
  LOAD = 'beers/LOAD',
  LOAD_SUCCESS = 'beers/LOAD_SUCCESS',
  LOAD_ERROR = 'beers/LOAD_ERROR',
  LOAD_MORE = 'beers/LOAD_MORE',
  LOAD_MORE_SUCCESS = 'beers/LOAD_MORE_SUCCESS',
  LOAD_MORE_ERROR = 'beers/LOAD_MORE_ERROR',
  GIVE = 'beers/GIVE',
  GIVE_SUCCESS = 'beers/GIVE_SUCCESS',
  GIVE_ERROR = 'beers/GIVE_ERROR',
  NEW_LOG = 'beers/NEW_LOG',
}
