update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new build to firebase"
  lane :alpha do
    match(
      type: "adhoc",
      readonly: true
    )

    build_app(
      workspace: "./ios/appdoki.xcworkspace",
      output_directory: "./ios",
      scheme: "appdoki",
      include_bitcode: true
    )

    firebase_app_distribution
  end

  desc "Push a new build to TestFlight"
  lane :beta do
    match(
      type: "appstore",
      readonly: true
    )

    build_app(
      workspace: "./ios/appdoki.xcworkspace",
      output_directory: "./ios",
      scheme: "appdoki",
      include_bitcode: true
    )

    upload_to_testflight
  end
end
